/**
 * Can this wallet pay a Midnight transaction fee at all?
 *
 * Fees on Midnight are paid in DUST, and DUST is *generated by holding NIGHT*
 * — it cannot be received or bought. But the NIGHT need not be on Midnight:
 * a Cardano stake holding cNIGHT can be registered to this wallet's dust
 * address (Path B), and the DUST then accrues here. So an address holding
 * only tokens (USDM, say) CAN have full fee capacity. That is why the guard
 * must read the merged Path A + Path B balance — the one the battery shows —
 * and not Nexus's Path-A `dustState`, which is computed from native NIGHT
 * registrations alone and reads zero for exactly these wallets. Observed on
 * mainnet 2026-09-16: a wallet with 3,381 DUST from cNIGHT, refused with
 * "You need NIGHT to send on Midnight".
 *
 * A ZERO FROM THE INDEXER IS NEVER A VERIFIED ZERO. Everything the wallet knows
 * about Path B comes from the Midnight indexer, and the indexer reports only the
 * generation that is running NOW: its `dustGenerations` query sums live generation
 * rows and excludes any row with a non-null `dtime` (midnight-indexer v4.3.0,
 * indexer-api/src/infra/storage/dust_generations.rs). It has no notion of spendable
 * DUST. DUST that was generated earlier is not erased when generation stops: the
 * ledger keeps decaying each output (`DustOutput::updated_value`), so it stays
 * spendable for a while. Two ordinary ways to get "all figures zero, but DUST in
 * hand":
 *   - the owner moves every backing cNIGHT away while the registration stays active
 *     (midnight-node's cnight-observation `handle_spend` emits the generation Destroy
 *     action without removing the mapping), so `dust/destination` answers
 *     `registered:true` with an active stake and four zeros;
 *   - a registration is removed, so `dust/destination` answers unregistered/zero.
 * The wallet has no balance source that counts existing DUST outputs, so it cannot
 * tell those wallets from one that truly has none. Refusing the send on such a zero
 * would block a wallet that can pay (review of Gero-Labs/gerowallet#1216, round 1
 * and round 2).
 *
 * So the guard is four-valued and only ever WARNS today. Once the merged balance
 * has been reported, a positive figure is `ok`; a zero is `unverified`: the send
 * surfaces tell the user the fee may not be payable and offer a sponsor wallet, but
 * do not disable Send, so the user can still try with their own DUST. `none` — the
 * only value that blocks — needs a caller to assert `verifiedZero`, which nothing
 * does yet; it is the hook for a future balance source that accounts for existing
 * DUST outputs.
 *
 * Without any check the send runs a long way before failing: it authorizes,
 * builds the transaction server-side, syncs the whole DUST ledger, and only
 * then stalls inside `dust.balanceTransactions`, which does not throw. Observed
 * on mainnet 2026-09-07 as a send that span on "Sign transaction" forever. That
 * is why the user is warned up front rather than told nothing.
 *
 * "We haven't computed DUST state yet" is NOT the same as "there is none", and
 * warning on the former would flash the notice on every send made before the
 * dust state lands, so `unknown` never warns and never blocks.
 */
import type { MidnightDustState } from './midnightTypes';

export type MidnightFeeCapacity =
  /** DUST present — the send may proceed (it still may not be *enough*). */
  | 'ok'
  /** VERIFIED zero: the send cannot possibly pay its fee. The only value that blocks. */
  | 'none'
  /**
   * The merged balance reads zero, but zero is not verified: the indexer reports live
   * generation, not spendable DUST (see the file header). Warn and offer a sponsor; do not block.
   */
  | 'unverified'
  /** Not yet known. Never block or warn on this. */
  | 'unknown';

/**
 * Path-A-only reading. Kept for callers that genuinely only have the store's
 * `dustState`; the send surfaces must use {@link midnightFeeCapacityLive}.
 *
 * Nothing outside this file's spec calls it or {@link blocksMidnightSend}, so it is left as
 * it was. A new caller must not refuse on its `none` unless the source of `current` accounts
 * for existing DUST outputs (see the file header).
 */
export function midnightFeeCapacity(
  dustState: MidnightDustState | null | undefined,
): MidnightFeeCapacity {
  if (!dustState) return 'unknown';
  // `current` is the spendable DUST balance in base units.
  if (typeof dustState.current !== 'bigint') return 'unknown';
  return dustState.current > 0n ? 'ok' : 'none';
}

/**
 * Whether the UI should refuse the send outright.
 *
 * Only `none` blocks: a non-zero balance that turns out to be too small for
 * this particular fee is the chain's call, not ours — we have no fee estimate
 * at this point and inventing one would reject valid sends.
 */
export function blocksMidnightSend(
  dustState: MidnightDustState | null | undefined,
): boolean {
  return midnightFeeCapacity(dustState) === 'none';
}

/** The live inputs the send guard needs, from `useMidnightDustLive`. */
export interface MidnightLiveFeeInputs {
  /** Merged Path A + Path B DUST balance in base units — the figure the battery shows. */
  dustBalance: bigint;
  /**
   * Both paths have REPORTED. Until Path B has answered, the merged balance
   * can read 0 for a wallet whose DUST comes entirely from Cardano, and
   * warning on that would flash the notice for the length of one poll.
   *
   * Reported is not verified: what Path B reports is a generation status, not a
   * spendable balance (see the file header).
   */
  settled: boolean;
  /**
   * The zero balance has been VERIFIED by a source that accounts for existing DUST
   * outputs. Nothing sets this today, so nothing is ever blocked: the hook for a
   * future balance source that counts spendable outputs, not just live generation.
   * Only consulted once `settled` and only while the balance reads zero.
   */
  verifiedZero?: boolean;
}

/**
 * Four-valued like {@link midnightFeeCapacity}, but over the merged live balance:
 * `unknown` until both paths have reported, `ok` for any positive balance, `none`
 * only for a zero the caller asserts is verified, and `unverified` for every other
 * zero. Only `none` blocks.
 */
export function midnightFeeCapacityLive(live: MidnightLiveFeeInputs | null | undefined): MidnightFeeCapacity {
  if (!live || !live.settled) return 'unknown';
  if (live.dustBalance > 0n) return 'ok';
  return live.verifiedZero === true ? 'none' : 'unverified';
}

/**
 * Whether the UI should refuse the send outright, judged on the merged live balance.
 * True only for a verified zero, so it is false for every reading the wallet can take today.
 */
export function blocksMidnightSendLive(live: MidnightLiveFeeInputs | null | undefined): boolean {
  return midnightFeeCapacityLive(live) === 'none';
}

/**
 * Whether the UI should warn that this wallet may not be able to pay the fee, and offer a
 * sponsor: an unverified zero, or a verified one. Never true for `unknown`. Does NOT mean
 * the send should be blocked; that is {@link blocksMidnightSendLive}.
 */
export function mayLackDustLive(live: MidnightLiveFeeInputs | null | undefined): boolean {
  const capacity = midnightFeeCapacityLive(live);
  return capacity === 'unverified' || capacity === 'none';
}
