/**
 * Can this wallet pay a Midnight transaction fee at all?
 *
 * Fees on Midnight are paid in DUST, and DUST is *generated by holding NIGHT*
 * — it cannot be received or bought. But the NIGHT need not be on Midnight:
 * a Cardano stake holding cNIGHT can be registered to this wallet's dust
 * address (Path B), and the DUST then accrues here. So an address holding
 * only tokens (USDM, say) CAN have full fee capacity. That is why the guard
 * must read the merged Path A + Path B balance — the one the battery shows —
 * and not Nexus's Path-A `dustState`, which is computed from native NIGHT
 * registrations alone and reads zero for exactly these wallets. Observed on
 * mainnet 2026-09-16: a wallet with 3,381 DUST from cNIGHT, refused with
 * "You need NIGHT to send on Midnight".
 *
 * Without this check the send runs a long way before failing: it authorizes,
 * builds the transaction server-side, syncs the whole DUST ledger, and only
 * then stalls inside `dust.balanceTransactions`, which does not throw. Observed
 * on mainnet 2026-09-07 as a send that span on "Sign transaction" forever.
 *
 * Deliberately three-valued. "We haven't computed DUST state yet" is NOT the
 * same as "there is none", and blocking a send on the former would break every
 * send made before the dust state lands.
 */
import type { MidnightDustState } from './midnightTypes';

export type MidnightFeeCapacity =
  /** DUST present — the send may proceed (it still may not be *enough*). */
  | 'ok'
  /** Known to be zero: the send cannot possibly pay its fee. */
  | 'none'
  /** Not yet known. Never block on this. */
  | 'unknown';

/**
 * Path-A-only reading. Kept for callers that genuinely only have the store's
 * `dustState`; the send surfaces must use {@link midnightFeeCapacityLive}.
 */
export function midnightFeeCapacity(
  dustState: MidnightDustState | null | undefined,
): MidnightFeeCapacity {
  if (!dustState) return 'unknown';
  // `current` is the spendable DUST balance in base units.
  if (typeof dustState.current !== 'bigint') return 'unknown';
  return dustState.current > 0n ? 'ok' : 'none';
}

/**
 * Whether the UI should refuse the send outright.
 *
 * Only `none` blocks: a non-zero balance that turns out to be too small for
 * this particular fee is the chain's call, not ours — we have no fee estimate
 * at this point and inventing one would reject valid sends.
 */
export function blocksMidnightSend(
  dustState: MidnightDustState | null | undefined,
): boolean {
  return midnightFeeCapacity(dustState) === 'none';
}

/** The two live inputs the send guard needs, from `useMidnightDustLive`. */
export interface MidnightLiveFeeInputs {
  /** Merged Path A + Path B DUST balance in base units — the figure the battery shows. */
  dustBalance: bigint;
  /**
   * Both paths have reported. Until Path B has answered, the merged balance
   * can read 0 for a wallet whose DUST comes entirely from Cardano, and
   * blocking on that would refuse a valid send for the length of one poll.
   */
  settled: boolean;
}

/**
 * Three-valued like {@link midnightFeeCapacity}, but over the merged live
 * balance. `unknown` until both paths have reported; never block on it.
 */
export function midnightFeeCapacityLive(live: MidnightLiveFeeInputs | null | undefined): MidnightFeeCapacity {
  if (!live || !live.settled) return 'unknown';
  return live.dustBalance > 0n ? 'ok' : 'none';
}

/** Whether the UI should refuse the send outright, judged on the merged live balance. */
export function blocksMidnightSendLive(live: MidnightLiveFeeInputs | null | undefined): boolean {
  return midnightFeeCapacityLive(live) === 'none';
}
