/**
 * Derive the DUST secret seed of a wallet OTHER than the one sending.
 *
 * Midnight fees are paid in DUST, which is generated by holding NIGHT and
 * cannot be transferred. A wallet holding only tokens therefore cannot send at
 * all — but a transaction's balancing splits by key: the DUST fee needs only a
 * DUST secret, while the inputs are signed with the sender's NightExternal
 * key. `BalanceAndSignUnshieldedTransferArgs` already keeps those two as
 * separate fields, so "sponsorship" is simply passing a different
 * `dustSecretSeed` than the wallet doing the signing.
 *
 * SECURITY. This decrypts a second wallet's mnemonic, so it is deliberately
 * narrow:
 *
 *  - The caller must supply THAT wallet's own credential. There is no path
 *    here that reuses the active wallet's password, and none that reads a
 *    cached secret — a sponsored send always costs an explicit unlock.
 *  - Only the DUST seed leaves this module. The mnemonic is dropped
 *    immediately and no other derived material (NightExternal key, Zswap
 *    viewing key, Cardano material) is returned or retained.
 *  - The returned seed is the CALLER'S to wipe, matching the contract the
 *    rest of the Midnight builder already documents for key material.
 *
 * This module deliberately does NOT decide *whether* sponsorship is allowed —
 * eligibility (same network, known non-zero DUST) is a separate concern.
 */
import { Blockchain } from '@/models/types';
import type { Wallet } from '@/models/types';

/** What the sponsor wallet needs to unlock. Exactly one applies. */
export interface SponsorCredential {
  /** Spending password, for a password-encrypted wallet. */
  readonly password?: string;
  /** WebAuthn PRF output, for a PassKey wallet. */
  readonly prfSecret?: Uint8Array;
}

export interface SponsorDustSeedRequest {
  /** The wallet paying the fee — never the wallet signing the inputs. */
  readonly sponsor: Wallet;
  /** Network of the transaction being sponsored. */
  readonly network: string;
  readonly credential: SponsorCredential;
}

/**
 * Reasons a wallet cannot act as a sponsor, as stable codes rather than
 * prose so callers can map them to translated copy.
 */
export type SponsorRejection =
  | 'not-midnight'
  | 'network-mismatch'
  | 'same-wallet'
  | 'missing-credential'
  | 'no-mnemonic';

export class SponsorNotEligibleError extends Error {
  constructor(readonly reason: SponsorRejection) {
    super(`Sponsor wallet is not eligible: ${reason}`);
    this.name = 'SponsorNotEligibleError';
  }
}

/**
 * Checks that hold regardless of DUST balance. Balance eligibility lives in
 * `midnightFeeCapacity`; these are the ones that would produce a malformed or
 * unsafe transaction rather than merely a failing one.
 *
 * `senderWalletId` is required so the "sponsor yourself" case is rejected
 * loudly: it would work, but it means the UI offered a pointless extra unlock
 * for a wallet that already had DUST.
 */
export function assertSponsorEligible(
  sponsor: Wallet,
  network: string,
  senderWalletId: number,
): void {
  if (sponsor.chain !== Blockchain.MIDNIGHT) throw new SponsorNotEligibleError('not-midnight');
  // Cross-network sponsorship is nonsense: DUST is per-network, and a
  // mainnet fee cannot pay for a preprod transaction.
  if (sponsor.network !== network) throw new SponsorNotEligibleError('network-mismatch');
  if (sponsor.id === senderWalletId) throw new SponsorNotEligibleError('same-wallet');
}

/**
 * Decrypt the sponsor's mnemonic with ITS OWN credential and derive only the
 * DUST seed.
 *
 * Returns the seed; the caller owns wiping it. Throws
 * {@link SponsorNotEligibleError} for a structurally invalid sponsor and a
 * plain Error for a wrong credential (the decrypt failure surfaces as-is so
 * the UI can say "wrong password" rather than something generic).
 */
export async function deriveSponsorDustSeed(
  req: SponsorDustSeedRequest,
  senderWalletId: number,
): Promise<Uint8Array> {
  const { sponsor, network, credential } = req;
  assertSponsorEligible(sponsor, network, senderWalletId);

  let mnemonic: string;
  if (sponsor.encryptionMethod === 'prf') {
    if (!credential.prfSecret) throw new SponsorNotEligibleError('missing-credential');
    if (!sponsor.prfEncryptedMnemonic) throw new SponsorNotEligibleError('no-mnemonic');
    if (!sponsor.webAuthnCredentialId) throw new SponsorNotEligibleError('no-mnemonic');
    const { decryptMnemonicWithPrfOutput } = await import('@/shared/utils/webauthn-prf');
    mnemonic = await decryptMnemonicWithPrfOutput(
      sponsor.prfEncryptedMnemonic,
      credential.prfSecret,
      sponsor.webAuthnCredentialId,
      sponsor.id.toString(),
    );
  } else {
    if (!credential.password) throw new SponsorNotEligibleError('missing-credential');
    if (!sponsor.encryptedMnemonic) throw new SponsorNotEligibleError('no-mnemonic');
    const { decrypt } = await import('@/shared/utils/crypto');
    mnemonic = decrypt(sponsor.encryptedMnemonic, credential.password);
  }

  try {
    const { deriveMidnightKeys } = await import('./midnightKeyManager');
    // skipCardano for the same reason the signing paths use it: the BG
    // bundle's pbkdf2/sha512 shim breaks on the Cardano BIP-32 derivation,
    // and a fee payment needs none of that material.
    const derived = await deriveMidnightKeys(mnemonic, sponsor.network, 0, { skipCardano: true });
    // Only the DUST seed escapes. Everything else derived here — the
    // NightExternal key above all — stays inside this function: the sponsor
    // authorises a fee, never a transfer.
    return derived.dustSecretKey;
  } finally {
    // Best effort. Strings are immutable in JS so this only drops the
    // reference; it does not scrub the backing memory. The real protection is
    // that the mnemonic is never returned, stored, or logged.
    mnemonic = '';
  }
}
