// @vitest-environment node
import { describe, expect, it } from 'vitest';
import * as legacy from '@midnight-ntwrk/ledger-v8';
import * as ledger from '@midnightntwrk/ledger-v9';
import fixture from './fixtures/nexus-ledger-signing.json';
import { midnightKeystore, schnorrHex, validateMidnightSigningSegments } from './midnightLedger';
import { deserializeLedger9Transaction, signLedger9Transaction } from './midnightLedger9';

// Generated by the real Nexus sidecar builder, including its controlled-indexer
// DUST path. See fixture.source for the generator; all keys/UTxOs are synthetic.
// Transfer segment indexes are input ordinals; registration index is intent 1.
const secret = Uint8Array.from(Buffer.from(fixture.secret, 'hex'));

describe('Nexus to wallet ledger signing contract', () => {
  for (const vector of fixture.transfers) {
    it(`${vector.network}: signs ${vector.count} ${vector.token.startsWith('00') ? 'NIGHT' : 'custom-token'} input(s) from Nexus`, async () => {
      expect(vector.segmentsToSign.map(segment => segment.index)).toEqual(Array.from({ length: vector.count }, (_, index) => index));
      if (vector.network === 'stagenet') {
        const signed = deserializeLedger9Transaction(vector.network, signLedger9Transaction(vector.network, vector.unprovenTxHex, secret));
        const intent = signed.intents!.get(1)!;
        const offer = intent.fallibleUnshieldedOffer ?? intent.guaranteedUnshieldedOffer!;
        const payload = intent.signatureData(1);
        expect(offer.inputs).toHaveLength(vector.count);
        expect(offer.signatures).toHaveLength(vector.count);
        for (const signature of offer.signatures) {
          expect(ledger.verifySignature({ tag: 'schnorr', value: fixture.publicKey }, payload, signature.value)).toBe(true);
        }
        for (const segment of vector.segmentsToSign) expect(segment.dataHex).toBe(Buffer.from(payload).toString('hex'));
      } else {
        const tx = legacy.Transaction.deserialize('signature', 'pre-proof', 'pre-binding', Buffer.from(vector.unprovenTxHex, 'hex'));
        const payload = tx.intents!.get(1)!.signatureData(1);
        const keystore = await midnightKeystore(secret, vector.network);
        const signature = schnorrHex(keystore.signData(payload));
        expect(legacy.verifySignature(fixture.publicKey, payload, signature)).toBe(true);
        for (const segment of vector.segmentsToSign) expect(segment.dataHex).toBe(Buffer.from(payload).toString('hex'));
      }
    });
  }

  it('validates and signs the actual beta.2 native DUST registration payload', async () => {
    const vector = fixture.registration;
    const segments = vector.segmentsToSign.map(segment => ({ ...segment, role: 'NightExternal' as const }));
    await expect(validateMidnightSigningSegments(vector.network, vector.unprovenTxHex, segments)).resolves.toBeUndefined();
    const keystore = await midnightKeystore(secret, vector.network);
    const payload = Buffer.from(segments[0].dataHex, 'hex');
    const signature = { tag: 'schnorr' as const, value: schnorrHex(keystore.signData(payload)) };
    expect(ledger.verifySignature({ tag: 'schnorr', value: fixture.publicKey }, payload, signature)).toBe(true);
    await expect(validateMidnightSigningSegments(vector.network, vector.unprovenTxHex, [{ ...segments[0], dataHex: '00' }])).rejects.toThrow('does not match');
  });
});
