/**
 * Can this wallet pay a Midnight transaction fee at all?
 *
 * Fees on Midnight are paid in DUST, and DUST is *generated by holding NIGHT*
 * — it cannot be received or bought. So an address holding only tokens (USDM,
 * say) has no fee capacity and cannot send anything, including those tokens.
 *
 * Without this check the send runs a long way before failing: it authorizes,
 * builds the transaction server-side, syncs the whole DUST ledger, and only
 * then stalls inside `dust.balanceTransactions`, which does not throw. Observed
 * on mainnet 2026-09-07 as a send that span on "Sign transaction" forever.
 *
 * Deliberately three-valued. "We haven't computed DUST state yet" is NOT the
 * same as "there is none", and blocking a send on the former would break every
 * send made before the dust state lands.
 */
import type { MidnightDustState } from './midnightTypes';

export type MidnightFeeCapacity =
  /** DUST present — the send may proceed (it still may not be *enough*). */
  | 'ok'
  /** Known to be zero: the send cannot possibly pay its fee. */
  | 'none'
  /** Not yet known. Never block on this. */
  | 'unknown';

export function midnightFeeCapacity(
  dustState: MidnightDustState | null | undefined,
): MidnightFeeCapacity {
  if (!dustState) return 'unknown';
  // `current` is the spendable DUST balance in base units.
  if (typeof dustState.current !== 'bigint') return 'unknown';
  return dustState.current > 0n ? 'ok' : 'none';
}

/**
 * Whether the UI should refuse the send outright.
 *
 * Only `none` blocks: a non-zero balance that turns out to be too small for
 * this particular fee is the chain's call, not ours — we have no fee estimate
 * at this point and inventing one would reject valid sends.
 */
export function blocksMidnightSend(
  dustState: MidnightDustState | null | undefined,
): boolean {
  return midnightFeeCapacity(dustState) === 'none';
}
