import { describe, expect, it } from 'vitest';
import { isInsufficientDust, shouldDiscardCheckpoint } from './midnightDustCheckpoint';

// The exact string the SDK threw on mainnet, four sends in a row, from a
// checkpoint written before the wallet's DUST registration had relayed.
const SDK_ERROR = new Error('Insufficient Funds: could not balance dust');

// Our own timeout copy, which describes the same condition in prose.
const TIMEOUT_ERROR = new Error(
  'Timed out computing the DUST fee for this transaction. This usually means '
  + 'the wallet has no spendable DUST — DUST is generated by holding NIGHT, so '
  + 'an address holding only tokens cannot pay fees.',
);

describe('isInsufficientDust', () => {
  it('recognises the SDK error seen on mainnet', () => {
    expect(isInsufficientDust(SDK_ERROR)).toBe(true);
  });

  it('recognises our timeout copy for the same condition', () => {
    expect(isInsufficientDust(TIMEOUT_ERROR)).toBe(true);
  });

  it('matches regardless of case', () => {
    expect(isInsufficientDust(new Error('INSUFFICIENT FUNDS'))).toBe(true);
  });

  it('accepts a thrown string, not only an Error', () => {
    expect(isInsufficientDust('could not balance dust')).toBe(true);
  });

  it('does not match unrelated failures', () => {
    // These must NOT discard a checkpoint: the sync progress is fine and
    // throwing it away costs a full ledger replay on the next send.
    expect(isInsufficientDust(new Error('unreachable'))).toBe(false);
    expect(isInsufficientDust(new Error('WASM memory access out of bounds'))).toBe(false);
    expect(isInsufficientDust(new Error('Invalid signature value'))).toBe(false);
  });

  it('does not throw on null or undefined', () => {
    expect(isInsufficientDust(null)).toBe(false);
    expect(isInsufficientDust(undefined)).toBe(false);
  });
});

describe('shouldDiscardCheckpoint', () => {
  it('discards when a resumed checkpoint could not pay the fee', () => {
    // The actual bug: resuming from a checkpoint written pre-registration
    // yields a fully synced wallet with nothing to spend, and the sync path
    // re-saves that same empty state every time.
    expect(shouldDiscardCheckpoint(SDK_ERROR, true)).toBe(true);
  });

  it('keeps the checkpoint when the attempt started cold', () => {
    // A cold start has no stale local state to blame. Discarding would force
    // a needless full ledger replay next send.
    expect(shouldDiscardCheckpoint(SDK_ERROR, false)).toBe(false);
  });

  it('keeps the checkpoint when the failure was not about DUST', () => {
    expect(shouldDiscardCheckpoint(new Error('network unreachable'), true)).toBe(false);
  });

  it('keeps the checkpoint on a cold start with an unrelated failure', () => {
    expect(shouldDiscardCheckpoint(new Error('network unreachable'), false)).toBe(false);
  });

  it('discards on the timeout variant too', () => {
    // The stall and the prompt throw are the same underlying condition; both
    // leave the wallet permanently stuck if the checkpoint survives.
    expect(shouldDiscardCheckpoint(TIMEOUT_ERROR, true)).toBe(true);
  });
});
