export enum MessageTypes {
  CREATE_NEW_WALLET = 'CREATE_NEW_WALLET',
  CREATE_NEW_HARDWARE_WALLET = 'CREATE_NEW_HARDWARE_WALLET',
  SIGN_TX = 'SIGN_TX',
  MULTISIG_TRANSACTION = 'MULTISIG_TRANSACTION',
  CREATE_MULTISIG_WALLET = 'CREATE_MULTISIG_WALLET',
}
